# Generated by Django 5.0.2 on 2024-03-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0002_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_poster',
            field=models.ImageField(default='staric/images/a.jpg', upload_to='movie_posters'),
        ),
    ]
