# Generated by Django 5.0.2 on 2024-03-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0003_alter_movies_movie_poster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
