# Generated by Django 5.0.2 on 2024-03-05 18:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0005_reviewraiting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewRaiting',
            new_name='ReviewRating',
        ),
    ]
