# Generated by Django 5.0.2 on 2024-03-06 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0006_rename_reviewraiting_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='raiting',
            new_name='rating',
        ),
    ]
