# Generated by Django 5.0.2 on 2024-03-07 09:12

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0008_delete_reviewrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=True, max_length=200, null=True, populate_from='movie_tittle', unique=True),
        ),
    ]
