# Generated by Django 5.0.2 on 2024-03-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaitingReview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='movie',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
