# Generated by Django 5.0.2 on 2024-03-05 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_image',
            name='confirm_password',
        ),
    ]
